config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations", sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                     }

  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "users/profile/:id", to: "users/sessions#show", as: "user_profiles"
    get "show_my_info/:id", to: "users#show_my_info", as: "show_my_info"
  end

  resources :users, path: "/users/mypage", only: [:show, :edit] do
    get "edit_address", to: "addresses#edit", as: "edit_address"
    patch "edit_address", to: "addresses#update"
    put "edit_address", to: "addresses#update"
    collection do
      post :search
    end
    resources :user, only: [:new, :create]
  end

  root "products#index"
  namespace :products do
    resources :searches, only: :index
  end
  resources :products do
    resources :buyers, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
    post "add", to: "likes#create"
    delete "/add", to: "likes#destroy"
    collection do
      get :search
    end
  end
  resources :categories, only: [:index, :show]
  resources :cards, only: [:index, :new, :create, :edit, :show, :destroy]
  resources :profiles
end

app/models/user.rb
class User < ApplicationRecord
  has_one :address, dependent: :destroy
  has_many :addresses , dependent: :destroy
  # accepts_nested_attributes_for :address //後から使用予定
  # has_many :cards, dependent: :destroy //後から使用予定
  has_many :buyed_products, foreign_key: "buyer_id", class_name: "Product"
  has_many :saling_products, -> { where("buyer_id is NULL") }, foreign_key: "user_id", class_name: "Product"
  has_many :sold_products, -> { where("buyer_id is not NULL") }, foreign_key: "user_id", class_name: "Product"
  has_many :products, dependent: :destroy
  has_many :sns_credentials
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :comments
  has_one :profile
  # has_many :comments //後から使用予定
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  # has_secure_password validations: false

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/
  VALID_KANA_REGEX = /\A[ァ-ンー－]+\z/

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates :first_name, presence: true, format: { with: VALID_NAME_REGEX, message: "は全角文字で入力して下さい。" }
  validates :last_name, presence: true, format: { with: VALID_NAME_REGEX, message: "は全角文字で入力して下さい。" }
  validates :first_kana, presence: true, format: { with: VALID_KANA_REGEX, message: "は全角片仮名で入力して下さい。" }
  validates :last_kana, presence: true, format: { with: VALID_KANA_REGEX, message: "は全角片仮名で入力して下さい。" }
  validates :birthday, presence: true
  

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      @sns_id = sns_info[:sns].id
      render template: 'users/registrations/new_user'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # before_action :set_user, only: [:edit, :update]
  before_action :set_parents, only: [:edit, :update]
  before_action :authenticate_user!
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    @user = User.find(current_user.id)
    
    binding.pry
    
  end

  # PUT /resource/password
  def update
    if current_user.update_with_password(user_params)
        redirect_to account_path
    else
        render :edit
    end
end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  protected

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
end

  # def set_user
  #   @user = User.find(params[:id])
  # end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]　/デフォルト記載
  # before_action :configure_account_update_params, only: [:update]　/デフォルト記載
  before_action :set_parents, only: [:edit, :update]

  def new
    @user = User.new
  end

  def new_user
    @user = User.new
  end

  def create_user
    if params[:sns_auth] == "true"
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    params[:user][:birthday] = birthday_join
    @user = User.new(sign_up_params)
    @address = Address.new
    if @user.valid?
      session["devise.regist_data"] = { user: @user.attributes }
      session["devise.regist_data"][:user]["password"] = params[:user][:password]
      session["devise.regist_data"][:user]["password_confirmation"] = params[:user][:password_confirmation]

      render :new_address
    else
      render :new_user
    end
  end

  def new_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    if @address.valid?
      @user.save
      @address = Address.new(address_params.merge(user_id: @user.id))
      @address.save
      session["devise.regist_data"]["user"].clear
      sign_in(:user, @user)
    else
      render :new_address
    end
  end

  def edit
    @profile = current_user.profile
    @user = User.find(current_user.id)
  end

  # PUT /resource/password
  def update
    @user = User.find(current_user.id)
    if current_user.update(user_params)
      # binding.pry
      return
    else
      render :edit
    end
  end

  protected

  def birthday_join
    @date = params[:birthday]
    if @date.values[0].empty?
      return
    elsif @date.values[1].empty?
      return
    elsif @date.values[2].empty?
      return
    end
    Date.new(@date.values[0].to_i, @date.values[1].to_i, @date.values[2].to_i)
  end

  # If you have extra params to permit, append them to the sanitizer. /デフォルト記載
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password, :email, :first_name, :last_name, :first_kana, :last_kana, :birthday])
  end

  # def sign_up_params　/デフォルト記載
  #   params.require(:user).permit(:name, :email, :first_name,:last_name, :first_kana, :last_kana, :birthday)
  # end

  def address_params
    params.require(:address).permit(:code, :area, :city, :village, :building, :destination_first, :destination_last, :destination_first_kana, :destination_last_kana, :area_kana, :city_kana, :village_kana, :building_kana, :phone_number)
  end

  def profile_params
    params.require(:user).permit(:profile, :icons, :password)
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def show
    @user = User.find(params[:id])
    @products = @user.products.order("created_at DESC")
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :show_my_info]
  before_action :set_parents, only: [:edit, :show, :update, :show_my_info]

  def edit
    @profile = current_user.profile
  end

  def update
    @user = current_user
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    if user_signed_in? && current_user.id == @user.id
      @products = @user.products.order("created_at DESC")
      @profile = current_user.profile
    else
      redirect_to root_path
    end
  end

  def show_my_info
      @profile = current_user.profile
      @address = Address.find(current_user.id)
  end

  def show_my_profile
      current_user
  end

  def search
    @products = []
    if params[:likes]
      p_list = params[:likes]
      @product = "お気に入り"
      ps = Like.where(user_id: p_list).order("created_at DESC")
      ps.each do |pr|
        @products += Product.includes(:images).where(id: pr.product_id)
      end
    elsif params[:saling]
      p_list = params[:saling]
      @product = "出品中の"
      @products += User.find(p_list).saling_products.order("created_at DESC")
    elsif params[:sold]
      p_list = params[:sold]
      @product = "売却済み"
      @products += User.find(p_list).sold_products.order("created_at DESC")
    elsif params[:buyed]
      p_list = params[:buyed]
      @product = "購入済み"
      @products += User.find(p_list).buyed_products.order("created_at DESC")
    end
    partial = render_to_string(partial: "any-products", locals: { product: @products })
    puts partial
    render json: { html: partial }
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :pssword)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end
end

app/views/users/_any-products.html.haml
%h2.container__inner__content__chapterHead
  = "#{current_user.name}さんの#{@product}商品一覧"
- @products.each do |product|
  .main__allProducts__productBox__productLists__productList
    - if product.buyer_id.present?
      .main__allProducts__productBox__productLists__productList__soldOut
        .main__allProducts__productBox__productLists__productList__soldOut__content SOLD
    = link_to product_path(product) do
      %figure.main__allProducts__productBox__productLists__productList--img
        = image_tag product.images[0].item.url
      .main__allProducts__productBox__productLists__productList--body
        .main__allProducts__productBox__productLists__productList__name
          = product.name
        .main__allProducts__productBox__productLists__productList__details
          %ul.productListDetails
            %li
              = "#{product.price.to_s(:delimited, delimiter: ',')}円"
            %li
              %i.fas.fa-star
              = "#{product.likes_count}"
          %p.productTax (税込)

app/views/users/_email-pass.html.haml
%h2.new_user__body__edit
  メールアドレス/パスワード
= form_for(@user, url: user_registration_path, html: {method: 'PUT', class: "user_form-field"}) do |form|
  .new_user__body__box
    .new_user__body__box__group
      .new_user__body__box__group__head
        %label
          メールアドレス
        %span
          任意
        %br
      = form.email_field :email, class: "new_user__body__box__group__form", placeholder: "PC・携帯どちらでも可"
    .new_user__body__box__group
      .new_user__body__box__group__head
        %label
          現在のパスワード
        %span
          任意
        %br
      = form.password_field :password, class: "new_user__body__box__group__form", placeholder: '現在のパスワード'
    .new_user__body__box__group
      .new_user__body__box__group__head
        %label
          新しいパスワード
        %span
          任意
        %br
      = form.password_field :password, class: "new_user__body__box__group__form", placeholder: '新しいパスワード'
    .new_user__body__box__group
      .new_user__body__box__group__head
        %label
          新しいパスワード（再入力）
        %span
          任意
        %br
      = form.password_field :password_confirmation, class: "new_user__body__box__group__form", placeholder: '新しいパスワード（再入力）'
    .user-mypage__main-content__content-form__content-box
      .user-mypage__main-content__content-form__content-box__btn
    = form.submit '更新する', class: 'btn-default btn'

app/views/users/_like-products.html.haml
%h2.container__inner__content__chapterHead
  = "#{current_user.name}さんのお気に入り一覧"
- @likes.each do |like|
  .main__allProducts__productBox__productLists__productList
    - if like.buyer_id.present?
      .main__allProducts__productBox__productLists__productList__soldOut
        .main__allProducts__productBox__productLists__productList__soldOut__content SOLD
    = link_to product_path(like) do
      %figure.main__allProducts__productBox__productLists__productList--img
        = image_tag like.images[0].item.url
      .main__allProducts__productBox__productLists__productList--body
        .main__allProducts__productBox__productLists__productList__name
          = like.name
        .main__allProducts__productBox__productLists__productList__details
          %ul.productListDetails
            %li
              = "#{like.price.to_s(:delimited, delimiter: ',')}円"
            %li
              %i.fas.fa-star
              = "#{like.likes_count}"
          %p.productTax (税込)

app/views/users/_mypage_products-lists.html.haml
%h2.container__inner__content__chapterHead
  = "#{@user.name}さんの全出品商品一覧"
- @products.each do |product|
  .main__allProducts__productBox__productLists__productList
    - if product.buyer_id.present?
      .main__allProducts__productBox__productLists__productList__soldOut
        .main__allProducts__productBox__productLists__productList__soldOut__content SOLD
    = link_to product_path(product) do
      %figure.main__allProducts__productBox__productLists__productList--img
        = image_tag product.images[0].item.url
      .main__allProducts__productBox__productLists__productList--body
        .main__allProducts__productBox__productLists__productList__name
          = product.name
        .main__allProducts__productBox__productLists__productList__details
          %ul.productListDetails
            %li
              = "#{product.price.to_s(:delimited, delimiter: ',')}円"
            %li
              %i.fas.fa-star
              = "#{product.likes_count}"
          %p.productTax (税込)

app/views/users/_side-bar.html.haml
.user-mypage__side-bar
  %h1.user-mypage__side-bar__title
    商品情報
  %ul.user-mypage__side-bar__content-box
    %li.user-mypage__side-bar__content-box__mypage
      = link_to user_path(current_user.id), class: 'user-mypage__side-bar__content-box__mypage__item' do
        マイページ
        %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = button_tag type: 'button', value: "#{current_user.id}", id: "likes-list" do
        お気に入り
      %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = button_tag type: 'button', value: "#{current_user.id}", id: "saling-list" do
        出品した商品 − 出品中
      %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = button_tag type: 'button', value: "#{current_user.id}", id: "sold-list" do
        出品した商品 - 売却済み
      %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = button_tag type: 'button', value: "#{current_user.id}", id: "buyed-list" do
        購入した商品 - 購入済み
      %i.fas.fa-chevron-right
  %h1.user-mypage__side-bar__title
    設定
  %ul.user-mypage__side-bar__content-box
    %li.user-mypage__side-bar__content-box__list
      - if @profile != nil && @profile.persisted?
        = link_to edit_profile_path(@profile), class: 'user-mypage__side-bar__content-box__mypage__item' do
          プロフィール
          %i.fas.fa-chevron-right
      - else
        = link_to new_profile_path(@profile), class: 'user-mypage__side-bar__content-box__mypage__item' do
          プロフィール
          %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = link_to user_edit_address_path(current_user.id), class: 'user-mypage__side-bar__content-box__mypage__item' do
        お届け先住所変更
        %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = link_to new_card_path, class: 'user-mypage__side-bar__content-box__mypage__item' do
        カード情報
        %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = link_to edit_user_registration_path, class: 'user-mypage__side-bar__content-box__mypage__item' do
        メール/パスワード
        %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = link_to show_my_info_path(current_user.id), class: 'user-mypage__side-bar__content-box__mypage__item' do
        本人情報
        %i.fas.fa-chevron-right
    %li.user-mypage__side-bar__content-box__list
      = link_to destroy_user_session_path, method: :delete, class: 'user-mypage__side-bar__content-box__mypage__item' do
        ログアウト
        %i.fas.fa-chevron-right

app/views/users/show.html.haml
= render 'products/shared/header'

%nav.breadCrumbs
  - breadcrumb :mypage
  = render "layouts/breadcrumbs"

%main.container
  .container__inner
    = render 'side-bar'

    .container__inner__content
      %section.container__inner__content
        - if params[:likes] || params[:saling] || params[:sold] || params[:buyed]
          .mypageProductLists#productsval
            = render partial: 'any-products', locals: { product: @products }
        - else
          .mypageProductLists#productsval
            = render 'mypage_products-lists'

= render 'products/shared/app_banner'

= render 'products/shared/footer'

= render 'products/shared/purchase_btn'

app/views/users/show_my_info.html.haml
= render 'products/shared/header'

%nav.breadCrumbs
  - breadcrumb :myinfo
  = render "layouts/breadcrumbs"

%main.container
  .container__inner
    = render 'side-bar'

    .container__inner__content
      %section.container__inner__content
        - if params[:likes] || params[:saling] || params[:sold] || params[:buyed]
          .mypageProductLists#productsval
            = render partial: 'any-products', locals: { product: @products }
        - else
          .mypageProductLists#productsval
            %h2.new_user__body__edit
              本人情報
            .new_user__body__box
              .new_user__body__box__group
                .new_user__body__box__group__head
                  %label
                    お名前
                  %br
                    = current_user.first_name
                    = current_user.last_name
              %br
              .new_user__body__box__group
                .new_user__body__box__group__head
                  %label
                    お名前（カナ）
                  %br
                    = current_user.first_kana
                    = current_user.last_kana
              %br
              .new_user__body__box__group
                .new_user__body__box__group__head
                  %label
                    生年月日
                  %br
                    = current_user.birthday
              %br
              .new_user__body__box__group
                .new_user__body__box__group__head
                  %label
                    郵便番号
                  %br
                    = "〒#{current_user.address.code}"




= render 'products/shared/app_banner'

= render 'products/shared/footer'

= render 'products/shared/purchase_btn'

app/views/users/update_address.html.haml
.new_user
  .new_user__head
    %h1
      = link_to (image_tag ("material/logo/logo.png"), size: "200x58"), root_path


  .new_user__body
    %h2.body_head 完了
    .new_user__body__box
      = link_to 'マイページへ戻る', user_path, class: 'btn-default btn'

  = render 'users/registrations/user_footer'