config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations", sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                     }

  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "users/profile/:id", to: "users/sessions#show", as: "user_profiles"
    get "show_my_info/:id", to: "users#show_my_info", as: "show_my_info"
  end

  resources :users, path: "/users/mypage", only: [:show, :edit] do
    get "edit_address", to: "addresses#edit", as: "edit_address"
    patch "edit_address", to: "addresses#update"
    put "edit_address", to: "addresses#update"
    collection do
      post :search
    end
    resources :user, only: [:new, :create]
  end

  root "products#index"
  namespace :products do
    resources :searches, only: :index
  end
  resources :products do
    resources :buyers, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
    post "add", to: "likes#create"
    delete "/add", to: "likes#destroy"
    collection do
      get :search
    end
  end
  resources :categories, only: [:index, :show]
  resources :cards, only: [:index, :new, :create, :edit, :show, :destroy]
  resources :profiles
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_cards, only: [:index, :edit]
  before_action :set_parents, only: [:new, :show]
  before_action :set_profile, only: [:new, :show]

  require "payjp"

  def index
    @users = User.all
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if card.exists?
  end

  def create #payjpとCardのデータベース作成
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
    #保管した顧客IDでpayjpから情報取得
    if params["payjp-token"].blank?
      redirect_to action: :new
    else
      customer = Payjp::Customer.create(
        card: params["payjp-token"],
        metadata: { user_id: current_user.id },
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user.id)
      else
        redirect_to action: :create
      end
    end
  end

  def edit
  end

  def show #Cardのデータpayjpに送り情報を取り出す
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @exp_month = @default_card_information.exp_month.to_s
      @exp_year = @default_card_information.exp_year.to_s.slice(2, 3)
      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266"
      when "MasterCard"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266"
      when "JCB"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266"
      when "American Express"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266"
      when "Diners Club"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266"
      when "Discover"
        @card_src = "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266"
      end
    else
      redirect_to action: :new
    end
  end

  def destroy #PayjpとCardデータベースを削除
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: :new
  end

  private

  def set_cards
    @cards = Card.all
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def set_profile
    @profile = current_user.profile
  end
end

app/views/cards/edit.html.haml
= render 'products/shared/header'

.user-mypage.clearfix
  = render 'users/side-bar'

  .user-mypage__main-content
    .user-mypage__main-content__content-title
      カード情報追加
    = form_with model: @card, class: 'user-mypage__main-content__content-form' do |form|
      .user-mypage__main-content__content-form__content-box
        .user-mypage__main-content__content-form__content-box__infomartion 
          カード番号
        = form.text_field :email , class: 'user-mypage__main-content__content-form__content-box__form', placeholder: '半角数字のみ'
      .user-mypage__main-content__content-form__content-box
        .user-mypage__main-content__content-form__content-box__infomartion
          有効期限
        = form.text_field :data, class: 'user-mypage__main-content__content-form__content-box__form__year'
        = form.text_field :data, class: 'user-mypage__main-content__content-form__content-box__form__month'
      .user-mypage__main-content__content-form__content-box        
        .user-mypage__main-content__content-form__content-box__infomartion         
          セキュリティーコード
        = form.password_field :password , class: 'user-mypage__main-content__content-form__content-box__form', placeholder: 'カード裏面の４桁または３桁の数字'
      .user-mypage__main-content__content-form__content-box
        .user-mypage__main-content__content-form__content-box__btn
        = form.submit '登録する', class: 'user-mypage__main-content__content-form__content-box__btn__send-btn'


= render 'products/shared/footer'

app/views/cards/index.html.haml
= render 'products/shared/header'

.user-mypage.clearfix
  = render 'users/side-bar'

  .user-mypage__main-content
    .user-mypage__main-content__content-title
      登録カード情報
    .user-mypage__main-content__content-form
      - @users.each do |user|
        .user-mypage__main-content__content-form__content-box
          .user-mypage__main-content__content-form__content-box__card-info
            = "カード番号  123456789012"
          .user-mypage__main-content__content-form__content-box__card-btn
            = link_to "削除", card_path(@cards), class: "user-mypage__main-content__content-form__content-box__btn__dele-btn"
      .user-mypage__main-content__content-form__content-box
        .user-mypage__main-content__content-form__content-box__btn
          = link_to  new_card_path, class: 'user-mypage__main-content__content-form__content-box__btn__add-btn' do
            #add-btn 追加
= render 'products/shared/footer'

app/views/cards/new.html.haml
= render 'products/shared/header'

%nav.breadCrumbs
  - breadcrumb :payment
  = render "layouts/breadcrumbs"

%main.container
  - flash.each do |notice, value|
    - notice
    %p.container__notice
      = value

  .container__inner
    = render 'users/side-bar'

    .container__inner__content
      %section.container__inner__content
        - if params[:likes] || params[:saling] || params[:sold] || params[:buyed]
          .mypageProductLists#productsval
            = render partial: 'any-products', locals: { product: @products }
        - else
          .mypageProductLists#productsval
            %h2.container__inner__content__chapterHead クレジットカード情報入力
            = form_with( url: cards_path, local: true, id: 'addCardForm', class: 'container__inner__content__form', html: { name: 'inputForm' } ) do |f|
              .container__inner__content__singleContent
                .container__inner__content__singleContent__formGroup
                  =f.label 'カード番号'
                  %span.container__inner__content__singleContent__formGroup__formRequire 必須
                  %br
                  = f.text_field :number, id: 'card_number', class: 'container__inner__content__singleContent__formGroup__inputDefault', placeholder: '半角数字のみ' , maxlength: '16', type: 'text'
                  %ul.container__inner__content__singleContent__formGroup__signupCardList
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__visa'
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__masterCard'
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__jcb'
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__americanExpress'
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__dinersclub'
                    %li
                      = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266', class: 'container__inner__content__singleContent__formGroup__signupCardList__discover'

                .container__inner__content__singleContent__formGroup.singleFormExpire
                  = f.label '有効期限'
                  %span.container__inner__content__singleContent__formGroup__formRequire 必須
                  %br
                  .container__inner__content__singleContent__formGroup__selectWrap
                    = f.select :exp_month, [ ['01','1'], ['02','2'], ['03','3'], ['04','4'], ['05','5'], ['06','6'], ['07','7'], ['08','8'], ['09','9'], ['10','10'], ['11','11'], ['12','12'] ], { prompt: '--' }, { id: 'exp_month', class: 'container__inner__content__singleContent__formGroup__selectWrap__selectDefault', type: 'text' }
                    %span 月
                  .container__inner__content__singleContent__formGroup__selectWrap
                    = f.select :exp_year, [ ['19','2019'], ['20','2020'], ['21','2021'], ['22','2022'], ['23','2023'], ['24','2024'], ['25','2025'], ['26','2026'], ['27','2027'], ['28','2028'], ['29','2029'] ], { prompt: '--' }, { id: 'exp_year', class: 'container__inner__content__singleContent__formGroup__selectWrap__selectDefault', type: 'text' }
                    %span 年

                .container__inner__content__singleContent__formGroup
                  = f.label 'セキュリティコード'
                  %span.container__inner__content__singleContent__formGroup__formRequire 必須
                  = f.text_field :cvc, id: 'cvc', class: 'container__inner__content__singleContent__formGroup__inputDefault', placeholder: 'カード背面3~4桁の番号', maxlength: '4'
                %br
                #card_token
                %br
                = f.submit '追加する', id: 'token_submit', class: 'container__inner__content__singleContent__formGroup__submitBtn'

= render 'products/shared/app_banner'

= render 'products/shared/footer'

= render 'products/shared/purchase_btn'

app/views/cards/show.html.haml
= render 'products/shared/header'

%nav.breadCrumbs
  - breadcrumb :payment
  = render "layouts/breadcrumbs"

%main.container
  .container__inner
    = render 'users/side-bar'

    .container__inner__content
      %section.container__inner__content
        - if params[:likes] || params[:saling] || params[:sold] || params[:buyed]
          .mypageProductLists#productsval
            = render partial: 'any-products', locals: { product: @products }
        - else
          .mypageProductLists#productsval
            %h2.container__inner__content__chapterHead 支払い方法
            .container__inner__content__singleInner
              %section
                .container__inner__content__singleInner__singleContent
                  %h3.container__inner__content__singleInner__singleContent__chapterSubHead クレジットカード一覧
                %ul
                  %li
                    = form_tag(card_path(current_user.id), method: :delete, id: 'charge-form', class: 'container__inner__content__singleInner__singleContent', name: "inputForm") do
                      = image_tag "#{@card_src}", alt: @card_brand,  id: 'card_image'
                      .container__inner__content__singleInner__singleContent__settingsPaymentNum
                        = "**** **** **** " + @default_card_information.last4
                      .container__inner__content__singleInner__singleContent__settingsPaymentNum
                        = @exp_month + " / " + @exp_year
                        %input{ type: "hidden", name: "card_id", value: "" }
                        %button.container__inner__content__singleInner__singleContent__settingsPaymentRemove 削除する

              .container__inner__content__singleInner__settingsNotRegist
                = link_to user_path(current_user.id) do
                  %span マイページへ戻る
                  %i.fas.fa-chevron-right

= render 'products/shared/app_banner'

= render 'products/shared/footer'

= render 'products/shared/purchase_btn'