config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations", sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                     }

  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "users/profile/:id", to: "users/sessions#show", as: "user_profiles"
    get "show_my_info/:id", to: "users#show_my_info", as: "show_my_info"
  end

  resources :users, path: "/users/mypage", only: [:show, :edit] do
    get "edit_address", to: "addresses#edit", as: "edit_address"
    patch "edit_address", to: "addresses#update"
    put "edit_address", to: "addresses#update"
    collection do
      post :search
    end
    resources :user, only: [:new, :create]
  end

  root "products#index"
  namespace :products do
    resources :searches, only: :index
  end
  resources :products do
    resources :buyers, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
    post "add", to: "likes#create"
    delete "/add", to: "likes#destroy"
    collection do
      get :search
    end
  end
  resources :categories, only: [:index, :show]
  resources :cards, only: [:index, :new, :create, :edit, :show, :destroy]
  resources :profiles
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  require 'payjp'#Payjpの読み込み
  before_action :set_card, :set_product

  def new
    @address = Address.find_by(user_id: current_user.id)
    @buyer_first_name = current_user.first_name
    @buyer_last_name = current_user.last_name
    @buyer_first_kana = current_user.first_kana
    @buyer_last_kana = current_user.last_kana
    @buyer_destination_first = @address.destination_first
    @buyer_destination_last = @address.destination_last
    @buyer_destination_fkana = @address.destination_first_kana
    @buyer_destination_lkana = @address.destination_last_kana

    if @card.present?
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @exp_month = @default_card_information.exp_month.to_s
      @exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266'
      when "MasterCard"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266'
      when "JCB"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266'
      when "American Express"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266'
      when "Diners Club"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266'
      when "Discover"
        @card_src = 'https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266'
      end
    else
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_card_path, notice: '商品を購入するには、クレジットカードの登録が必要です'
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_PRIVATE_KEY]
    Payjp::Charge.create(
      :amount => @product.price, #支払金額を引っ張ってくる
      :customer => @card.customer_id,  #顧客ID
      :currency => 'jpy',              #日本円
    )
    @product.update(buyer_id: current_user.id)
    @parents = Category.where(ancestry: nil)
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/views/buyers/create.html.haml
.form
  = render 'shared/header'

  .form_body
    .buyContent
      .buyContent__container
        .buyContent__container__inner
          %h1.buyContent__container__inner__attention
            %i.far.fa-clock
              発送をお待ちください
          %h2.buyContent__container__inner__title 購入が完了しました

          .buyContent__container__inner__product
            .buyContent__container__inner__product__productImage
              = image_tag "#{@product.images[0].item.url}"
            .buyContent__container__inner__product__productDetail
              %p.buyContent__container__inner__product__productDetail__productName
                = @product.name
              %br
              %p.buyContent__container__inner__product__productDetail__buyPrice
                = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
              %br
              %p.buyContent__container__inner__product__productDetail__shippingFree (税込) 送料込み

          .buyContent__container__inner__paymentAmount
            %form.buyContent__container__inner__paymentAmount__buyForm
              .buyContent__container__inner__paymentAmount__buyForm__left
                支払金額
              .buyContent__container__inner__paymentAmount__buyForm__right
                = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"

          .buyContent__container__inner__returnBtn
            = link_to "商品詳細ページへ戻る", product_path(@product.id)

= render 'products/shared/footer'

app/views/buyers/done.html.haml
%h1.buy-content__attention
  %i.far.fa-clock
    発送をお待ちください
  %h2.buy-content__attention__title
    購入が完了しました
  .buy-content__item
    .buy-content__item__inner
      .buy-item-main
        .buy-item-image
          = image_tag "#{@product.images[0].item.url}", size: '64x64', class: 'buydetails-contet__image'
        .buy-item-detail
          .buy-item-name
            = @product.name
            %p.buy-price
              %span
                = "¥#{@product.price.to_s}"
              %span
                .shipping-free (税込) 送料込み
  .buy-content__item
    %form.buy-form
      .buy-price-table
        .buy-price-table__left
          支払金額
        .buy-price-table__right
          = "¥#{@product.price.to_s}"
      .buy-content__user-info__submit
        = link_to "トップページへ戻る", root_path, class: 'buy-content__user-info__submit__button'

app/views/buyers/index.html.haml
%h2.buy-content__title
  購入内容の確認
.buy-content__item
  .buy-content__item__inner
    .buy-item-main
      .buy-item-image
        = image_tag "#{@product.images[0].item.url}", size: '64x64', class: 'buydetails-contet__image'
      .buy-item-detail
        .buy-item-name
          = @product.name
          %p.buy-price
            = "¥#{@product.price.to_s}"
            %span.shipping-free (税込) 送料込み
.buy-content__item
  %form.buy-form
    .buy-price-table
      .buy-price-table__left
        支払金額
      .buy-price-table__right
        = "¥#{@product.price.to_s}"
.buy-content__user-info
  .buy-content__user-info__inner
    %h3 支払方法
    .user-info-update
      = link_to '変更する', '#'
    .user-info-text
    - if @default_card_information.blank?
      %br
    - else
      = "**** **** **** " + "#{@default_card_information.last4}"
      %br
      = "有効期限 " + @exp_month + " / " + @exp_year
      %br
.buy-content__user-info
  .buy-content__user-info__inner              
    %h3 配送先
    .user-info-update
      = link_to '変更する', '#'
    .user-info-text
      = "〒#{@address.code} - 4567"
      %br
      = @address.area + @address.city + @address.village + @address.building
      %br
      = @buyer_first_name + @buyer_last_name
      = form_tag(action: :pay, method: :post) do
        %button.buy-button{type:"submit"} 購入する

app/views/buyers/new.html.haml
.form
  = render 'shared/header'

  .form_body
    #product_form
      .purchase-box
        #product-about
          #product-about__title
            購入内容の確認
        #product-about
          #product-about__contents
            .buyContent__container__inner__product__productImage
              = image_tag "#{@product.images[0].item.url}"
            .discription
              = @product.name
              %br
              %a 送料込み（税込み）
              = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
        #product-about
          .purchase-amount
            .purchase-amount__left
              %a 支払金額
            .purchase-amount__right
              = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
        #product-about
          .discription
            .discription__top
              .discription__top__left
                支払方法
              .discription__top__right
                = link_to '変更する', card_path(current_user.id)
                %i.fas.fa-chevron-right
            .discription__bottom
              - if @default_card_information.blank?
                %br
              - else
                クレジットカード
                %br
                = "**** **** **** " + "#{@default_card_information.last4}"
                %br
                = "有効期限 " + @exp_month + " / " + @exp_year
                %br
              = image_tag "#{@card_src}", alt: @card_brand,  id: 'card_image'
        #product-about
          .discription
            .discription__top
              .discription__top__left
                配送先
              .discription__top__right
                = link_to '変更する', user_edit_address_path(current_user.id)
                %i.fas.fa-chevron-right
            .discription__bottom
              = "〒#{@address.code}"
              %br
              = @address.area_kana + @address.city_kana + @address.village_kana + @address.building_kana
              %br
              = @address.area + @address.city + @address.village + @address.building
              %br
              %br
              %br
            - if @address.phone_number.present?
              .discription__top__left 連絡先
              %br
              = @address.phone_number
              %br
              %br
              %br
            .discription__top__left 送付先氏名
            %br
            .discription__top__left
              - if @buyer_destination_fkana.present? && @buyer_destination_lkana.present?
                = @buyer_destination_fkana + @buyer_destination_lkana
              - elsif @buyer_destination_fkana.present?
                = @buyer_destination_fkana + @buyer_last_kana
              - elsif @buyer_destination_lkana.present?
                = @buyer_first_kana + @buyer_destination_lkana
              - else
                = @buyer_first_kana + @buyer_last_kana
            .discription__top__left
              - if @buyer_destination_first.present? && @buyer_destination_last.present?
                = @buyer_destination_first + @buyer_destination_last
              - elsif @buyer_destination_first.present?
                = @buyer_destination_first + @buyer_last_name
              - elsif @buyer_destination_last.present?
                = @buyer_first_name + @buyer_destination_last
              - else
                = @buyer_first_name + @buyer_last_name
        #product-about
          .discription
            = form_tag(action: :create, method: :post) do
              %button.discription__btn-default{type:"submit"} 購入する

  = render 'shared/footer'