config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations", sessions: "users/sessions",
                       omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations",
                     }

  devise_scope :user do
    get "new_user", to: "users/registrations#new_user"
    post "new_user", to: "users/registrations#create_user"
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
    get "users/profile/:id", to: "users/sessions#show", as: "user_profiles"
    get "show_my_info/:id", to: "users#show_my_info", as: "show_my_info"
  end

  resources :users, path: "/users/mypage", only: [:show, :edit] do
    get "edit_address", to: "addresses#edit", as: "edit_address"
    patch "edit_address", to: "addresses#update"
    put "edit_address", to: "addresses#update"
    collection do
      post :search
    end
    resources :user, only: [:new, :create]
  end

  root "products#index"
  namespace :products do
    resources :searches, only: :index
  end
  resources :products do
    resources :buyers, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
    post "add", to: "likes#create"
    delete "/add", to: "likes#destroy"
    collection do
      get :search
    end
  end
  resources :categories, only: [:index, :show]
  resources :cards, only: [:index, :new, :create, :edit, :show, :destroy]
  resources :profiles
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  belongs_to :category
  has_many :images, dependent: :destroy
  belongs_to :buyer, class_name: "User"
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :postage
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shippingday

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  scope :with_keywords, -> keywords {
    if keywords.present?
      columns = [:name, :brand]
      where(keywords.to_s.split(/[[:blank:]]+/).reject(&:empty?).map {|keyword|
        columns.map { |a| arel_table[a].matches("%#{keyword}%") }.inject(:or)
      }.inject(:or))
    end
  }

  accepts_nested_attributes_for :images, allow_destroy: true,reject_if: proc { |attributes| attributes['item'].blank?}
  validates :images, presence: { message: "は1枚以上10枚以下のアップロードが必要です" }
  validates :name, presence: { message: "は必須です" }
  validates :detal, presence: { message: "は必須です" }
  validates :category_id, presence: { message: "を選択してください" }
  validates :condition_id, presence: { message: "を選択してください" }
  validates :postage_id, presence: { message: "を選択してください" }
  validates :prefecture_id, presence: { message: "を選択してください" }
  validates :shippingday_id, presence: { message: "を選択してください" }
  validates :price, presence: { message: "を入力してください" }

  def self.search(search)
    return Product.all unless search
    Product.where('name LIKE(?)', "%#{search}%")
  end

  def previous
    Product.where('id < ?', self.id).order('id DESC').first
    end

    def next
    Product.where('id > ?', self.id).order('id ASC').first
    end
end

app/controllers/products/searches_controller.rb
class Products::SearchesController < ApplicationController
  before_action :set_search

  def index
    @parents = Category.where(ancestry: nil)
    @products = []
    categories = []
    if params[:keyword]
      @search_word = params[:keyword]
      nil if @search_word == ""
      split_keyword = @search_word.to_s.split(/[[:blank:]]+/)

      split_keyword.each do |keyword|
        next if keyword == ""
        @products += Product.where("name LIKE(?) OR brand LIKE(?)", "%#{keyword}%", "%#{keyword}%").order(created_at: :desc)
      end

      split_keyword.each do |keyword|
        categorys = Category.where("name LIKE(?)", "%#{keyword}%")
        categorys.each do |category|
          if category.has_children?
            category_ids = category.descendants
            categories.push(Product.includes(:images).order("created_at DESC").where(category_id: category_ids)).flatten!
          else
            categories.push(Product.includes(:images).order("created_at DESC").where(category_id: category)).flatten!
          end
        end
      end
      @products.push(categories).flatten!
    else
      if params.dig(:q, :keywords).present?
        cates = Category.with_keywords(params.dig(:q, :keywords))
        cates.each do |cate|
          if cate.has_children?
            cate_ids = cate.descendants
            @c = Product.includes(:images).order("created_at DESC").where(category_id: cate_ids).ransack(params[:q])
            categories += @c.result(distinct: true)
          else
            @c = Product.includes(:images).order("created_at DESC").where(category_id: cate).ransack(params[:q])
            categories += @c.result(distinct: true)
          end
        end
        @products.push(categories).flatten!
      end
      @searches = Product.with_keywords(params.dig(:q, :keywords)).ransack(params[:q])
      @products += @searches.result(distinct: true)
      if params[:q][:category_id_in].present?
        @category = Category.find(params[:q][:category_id_in])
        if @category.has_children?
          @products += Product.includes(:images).order("created_at DESC").where(category_id: @category.descendants)
        else
          @products += Product.includes(:images).order("created_at DESC").where(category_id: @category)
        end
      end

      if params[:q][:sorts] == "id desc"
        @products.sort_by! { |a| a[:id] }.reverse!
      elsif params[:q][:sorts] == "price asc"
        @products.sort_by! { |a| a[:price] }
      elsif params[:q][:sorts] == "price desc"
        @products.sort_by! { |a| a[:price] }.reverse!
      elsif params[:q][:sorts] == "updated_at asc"
        @products.sort_by! { |a| a[:updated_at] }
      elsif params[:q][:sorts] == "updated_at desc"
        @products.sort_by! { |a| a[:updated_at] }.reverse!
      elsif params[:q][:sorts] == "likes_count desc"
        @products.sort_by! { |a| a[:likes_count] }.reverse!
      end

      @checked = "checked" if params[:q][:condition_id_true]
      @checkeds = "checked" if params[:q][:postage_id_true]
    end
    @products.uniq!
  end

  private

  def set_search
    @search = Product.ransack(params[:q])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :new, :create, :search]
  before_action :set_products, only: [:index, :show]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_parents, only: [:index, :show, :new, :create, :edit, :update]

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    @images = Image.limit(3).order(id: "DESC")
  end

  def new
    @product = Product.new
    @product.images.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      return
    else
      @product.images.new
      render :new
    end
  end

  def edit
    if user_signed_in? && current_user.id == @product.user_id
      return
    else
      redirect_to product_path
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def show
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    @images = @product.images
    @category = @product.category
    @parent = @category.root
    @children = @category.parent
    @products = Product.includes(:images).order("created_at DESC").where(category_id: @parent.descendants).where.not(category_id: @category)
    @likes = Like.where(product_id: @product.id).count
    @likes = 0 if @likes.nil?
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      redirect_to product_path
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json do
        if params[:parent_id]
          @childrens = Category.find(params[:parent_id]).children
        elsif params[:children_id]
          @grandChilds = Category.find(params[:children_id]).children
        elsif params[:gcchildren_id]
          @parents = Category.where(id: params[:gcchildren_id])
        elsif params[:keyword]
          @keywords = params[:keyword]
          return nil if @keywords == ""
          @allProducts = []
          @keywords.split(/[[:blank:]]+/).each do |keyword|
            @allProducts += Product.all.where("name LIKE(?) OR brand LIKE(?)", "%#{keyword}%", "%#{keyword}%").order(created_at: :desc)
          end
          @allProducts.uniq!

          @allCategorys = []
          @keywords.split(/[[:blank:]]+/).each do |keyword|
            @allCategorys += Category.where("name LIKE(?)", "%#{keyword}%")
          end
          @allCategorys.uniq!
        elsif params[:userid]
          @user = User.where(id: params[:userid])
        end
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :brand, :size, :prefecture_id, :condition_id, :postage_id, :shippingday_id, :detal, :category_id, :buyer_id, images_attributes: [:item, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_products
    @products = Product.includes(:images).order("created_at DESC")
  end

  def move_to_index
    redirect_to user_session_path unless user_signed_in?
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end
end

app/views/products/create.html.haml
.form
  = render 'shared/header'

  .form_body
    %h2.product_confirm 商品を出品しました！
    %h2.topback
      = link_to products_path do
        トップページへ戻る
    %h3.add_product
      = link_to new_product_path(@product) do
        さらに出品する

  = render 'shared/footer'

app/views/products/edit.html.haml
.form
  = render 'shared/header'

  .form_body
    %h2 商品の編集
    = render 'products/shared/form', product: @product

  = render 'shared/footer'

app/views/products/index.html.haml
= render 'products/shared/header'

.main
  %section.main__mainVisual
    .main__mainVisual__content
      %h2.main__mainVisual__content__subTitle
        %br
        人生を変えるフリマアプリ
      %p.main__mainVisual__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main__mainVisual__content__btn
        = link_to '#', class: 'main__mainVisual__content__btn__aBtn' do
          = image_tag 'app-store.png'
        = link_to '#', class: 'main__mainVisual__content__btn__gBtn' do
          = image_tag 'google-play.png'
    .main__mainVisual__picture

  %section.main__topIntroduction
    %h2.main__topIntroduction__subTitle FURIMAが選ばれる3つの理由
    %ul.main__topIntroduction__lists
      %li.main__topIntroduction__lists__list
        .main__topIntroduction__lists__list__pict
          %span.main__topIntroduction__lists__list__pict__number 1
          = image_tag 'material/pict/pict-reason-01.jpg'
        %h3.main__topIntroduction__lists__list__text
          %span 3分
          ですぐに出品
        %p.main__topIntroduction__lists__list__description スマホで入力するだけで簡単に出品できる！

      %li.main__topIntroduction__lists__list
        .main__topIntroduction__lists__list__pict
          %span.main__topIntroduction__lists__list__pict__number 2
          = image_tag 'material/pict/pict-reason-02.jpg'
        %h3.main__topIntroduction__lists__list__text
          %span シンプル
          で使いやすい
        %p.main__topIntroduction__lists__list__description めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.main__topIntroduction__lists__list
        .main__topIntroduction__lists__list__pict
          %span.main__topIntroduction__lists__list__pict__number 3
          = image_tag 'material/pict/pict-reason-03.jpg'
        %h3.main__topIntroduction__lists__list__text
          手数料
          %span 業界最安
        %p.main__topIntroduction__lists__list__description 最大3%でお得に出品&購入！

  %section.main__topMiddleDl
    .main__topMiddleDl__inner
      %h2.main__topMiddleDl__inner__subTitle 会員数日本一位
      %p.main__topMiddleDl__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__topMiddleDl__inner__btn
        = link_to '#' do
          = image_tag 'app-store.png', class: 'main__topMiddleDl__inner__btn__aBtn'
        = link_to '#' do
          = image_tag 'google-play.png', class: 'main__topMiddleDl__inner__btn__gBtn'

  %section.main__topKeyFeatures
    %h2.main__topKeyFeatures__head FURIMAの特徴
    .main__topKeyFeatures__items
      %section.main__topKeyFeatures__items__item
        %figure.main__topKeyFeatures__items__item__img
          = image_tag 'material/icon/icon-01.png'
        %h3.main__topKeyFeatures__items__item__subTitle 簡単に売り買いできる
        %p.main__topKeyFeatures__items__item__detail スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      %section.main__topKeyFeatures__items__item
        %figure.main__topKeyFeatures__items__item__img
          = image_tag 'material/icon/icon-03.png'
        %h3.main__topKeyFeatures__items__item__subTitle 売上金は即日振込みに対応
        %p.main__topKeyFeatures__items__item__detail 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

      %section.main__topKeyFeatures__items__item
        %figure.main__topKeyFeatures__items__item__img
          = image_tag 'material/icon/icon-04.png'
        %h3.main__topKeyFeatures__items__item__subTitle 様々な支払いに対応
        %p.main__topKeyFeatures__items__item__detail お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.main__allProducts
    .main__allProducts__head 商品一覧
    .main__allProducts__productBox
      .main__allProducts__productBox__productHead
        = link_to '#' do
          %h3.main__allProducts__productBox__productHead__title 投稿商品
      .main__allProducts__productBox__productLists
        = render 'products/shared/product_list'

= render 'products/shared/app_banner'

= render 'products/shared/footer'

= render 'products/shared/purchase_btn'

app/views/products/new.html.haml
.form
  = render 'shared/header'

  .form_body
    %h2 商品登録
    = render 'products/shared/form', product: @product

  = render 'shared/footer'

app/views/products/search.html.haml
= render 'products/shared/header'
.Search
  .Search__Result
    - if params[:q]['name_cont'] == ""
      = "検索キーワードがありません。"

    - elsif @search.result.present?
      .Search__Result__title
        = "「#{params[:q][:name_cont]}」の検索結果: #{@search.result.count}個"
      .Search__Result__content
        - @product.each do |product|
          %p
            = product.name

    - else
      = "検索に一致する商品はありませんでした"

app/views/products/show.html.haml
= render 'products/shared/header'

%nav.breadCrumbs
  - breadcrumb :product
  = render "layouts/breadcrumbs"

.showMain
  .showMain__content
    .showMain__content__topContent
      .showMain__content__topContent__itemBox
        %h2.showMain__content__topContent__itemBox__name
          = @product.name
        .showMain__content__topContent__itemBox__body
          .showMain__content__topContent__itemBox__body__pic
            = image_tag @product.images[0].item.url, class: "mainImg"
            .showMain__content__topContent__itemBox__body__pic__sub
              - @product.images.each_with_index do |image|
                = image_tag image.item.url, class: "subImg"
        .showMain__content__topContent__itemBox__price
          %span
            = "¥#{@product.price.to_s(:delimited, delimiter: ',')}"
          .showMain__content__topContent__itemBox__price__detail
            %span (税込)
            %span 送料込み
          - if @product.buyer_id.present?
            .showMain__content__topContent__itemBox__soldOut
              SOLD OUT
          - elsif user_signed_in? && current_user.id != @product.user_id
            .showMain__content__topContent__itemBox__purchaseBtn
              = link_to new_product_buyer_path(@product.id) do
                %input{type: "button", value: "購入画面に進む"}
          - elsif user_signed_in? && current_user.id == @product.user_id
            .showMain__content__topContent__itemBox__purchaseBtn 出品中
          - else
            .showMain__content__topContent__itemBox__purchaseBtn
              = link_to user_session_path do
                %input{type: "button", value: "購入画面に進む"}
        .showMain__content__topContent__itemBox__itemDetail
          = @product.detal
        .showMain__content__topContent__itemBox__table
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  = link_to user_profiles_path(@product.user.id) do
                    = @product.user.name
              %tr
                %th カテゴリー
                %td
                  = link_to category_path(@product.category.root.id) do
                    = @parent.name
                  %br
                  = link_to category_path(@product.category.parent.id) do
                    %i.fas.fa-angle-right
                    %span
                      = @children.name
                  %br
                  = link_to category_path(@product.category.id) do
                    %i.fas.fa-angle-right
                    %span
                      = @category.name
              %tr
                %th ブランド
                %td
                  = @product.brand
              %tr
                %th 商品サイズ
                %td
                  = @product.size
              %tr
                %th 商品の状態
                %td
                  = @product.condition.name
              %tr
                %th 配送料の負担
                %td
                  = @product.postage.name
              %tr
                %th 発送元の地域
                %td
                  = @product.prefecture.name
              %tr
                %th.showMain__content__topContent__itemBox__table__title 発送日の目安
                %td.showMain__content__topContent__itemBox__table__data
                  = @product.shippingday.name
        .showMain__content__topContent__itemBox__optionalArea
          %ul
            - if user_signed_in?
              %li.showMain__content__topContent__itemBox__optionalArea__likeBtn
                %i{id:"like-btn-#{@product.id}"}
                  = render 'likes/like', product: @product
            - else
              %li.showMain__content__topContent__itemBox__optionalArea__likeBtn{title:"ログインが必要です"}
                %i{id:"like-btn-#{@product.id}"}
                  %i.fa-lg.fas.fa-star.faa-ring.animated.icon-btn
                  %span.likes-text
                    = "お気に入り #{@product.likes.count}"
          %ul
            %li.showMain__content__topContent__itemBox__optionalArea__optionalBtn
              = link_to '#' do
                %i.fa.fa-flag
                不適切な商品の通報

      .showMain__content__topContent__commentBox
        .comments
          コメント一覧
        - if @comments.exists?
          - @comments.each do |c|
            .comments__box
              = link_to c.user.name, user_profiles_path(c.user.id), class: "comments__box__name"
              - if c.user.id === @product.user.id
                .comments__box__name__mark 出品者
              .comments__box__text
                %p
                  = c.text
        - else
          .comments__box
            .comments__box__noComment
              ＊まだコメントはありません。
        - if current_user
          = form_with(model: [@product, @comment], local: true, id: "new_comment") do |f|
            = f.text_area :text, id: :count_comment, placeholder: "コメントする", maxlength: "400", class: "showMain__content__topContent__commentBox__textField", rows: "4"
            .showMain__content__topContent__commentBox__noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            - if @product.buyer_id.present?
              .showMain__content__topContent__commentBox__submitBtnSold
                売り切れのためコメントできません
            -else
              = button_tag type: 'submit', class: 'showMain__content__topContent__commentBox__submitBtn' do
                %i.fa.fa-comment
                コメントする
        - else
          .showMain__content__topContent__commentBox__noticeMsg
            ＊コメントの投稿には新規登録/ログインが必要です。

      %ul.showMain__content__links
        - if @product.previous.present?
          %li
            = link_to product_path(@product.previous) do
              %i.fa.fa-angle-left
              %span 前の商品

        - if @product.next.present?
          %li
            = link_to product_path(@product.next) do
              %span 後ろの商品
              %i.fa.fa-angle-right

      .showMain__content__relatedItems
        = link_to category_path(@product.category.root.id), class: 'showMain__content__relatedItems__category' do
          = "#{@parent.name}をもっと見る"
        .showMain__content__relatedItems__productLists
          = render 'products/shared/product_list'
      .backpage
        %input{onclick: "history.back()", type: "button", value: "前のページへ戻る"}

= render 'products/shared/app_banner'

= render 'products/shared/footer'

- if user_signed_in? && current_user.id == @product.user_id
  = render 'products/shared/purchase_btn_edit'
  = render 'products/shared/purchase_btn'
- else
  = render 'products/shared/purchase_btn'